### PR TITLE
Ignore composer-generated files

### PR DESCRIPTION
**Pull request by svenluijten**

### CODE REVIEW

**Comment by svenluijten** [comment]
Bump 🙂 Let me know if you want this, or if you need me to make some edits.

**Comment by svenluijten** [comment]
Any reason this was closed?

**Comment by msonowal** [comment]
@svenluijten lock should be there

**Comment by svenluijten** [comment]
It's ignored when installing packages via `composer require` anyway. The version constraints in `composer.json` should be strict enough to not allow breaking changes.

**Pull request closed without merging**
